name       : nuget
version    : 2.11
release    : 1
source     :
    - http://stroblindustries.com/solus-tarballs/nuget2-2.11.tar.xz : 38afb04a4f15a0c40a5a494d911146f76391d50c2c3f3ae46eb9f48ff6cb8796
license    : Apache-2.0
summary    : Package manager for .NET.
description: |
    Package manager for .NET.
builddeps  :
    - pkgconfig(mono)
rundeps    :
    - mono
build      : |
    xbuild /p:Configuration=Release xdt/XmlTransform/Microsoft.Web.XmlTransform.csproj
    xbuild Build/Build.proj /p:Configuration=Release /p:TreatWarningsAsErrors=false /tv:4.0 /p:TargetFrameworkVersion=v4.5 /p:Configuration="Mono Release" /t:BuildMono
install    : |
    install -Dm0644 $srcdir/src/CommandLine/obj/Mono\ Release/NuGet.exe $installdir/%libdir%/nuget/NuGet.exe
    install -Dm0644 $srcdir/src/Core/obj/Mono\ Release/NuGet.Core.dll $installdir/%libdir%/nuget/
    install -Dm0644 $srcdir/xdt/XmlTransform/obj/Release/Microsoft.Web.XmlTransform.dll $installdir/%libdir%/nuget/
    install -Dm0755 $pkgfiles/nuget $installdir/usr/bin/nuget
