name       : nuget
version    : 5.6.0.6532
release    : 4
source     :
    - git|https://github.com/NuGet/NuGet.Client : 5.6.0.6532
license    : Apache-2.0
component  : programming.tools
summary    : Package manager for .NET
description: |
    The package manager for .NET. The NuGet Command Line Interface (CLI), nuget, provides the full extent of NuGet functionality to install, create, publish, and manage packages without making any changes to project files.
networking : yes
builddeps  :
    - mono-msbuild
rundeps    :
    - mono
setup      : |
    cert-sync --user /etc/ssl/certs/ca-certificates.crt
    %patch -p1 < $pkgfiles/ChangeILMergeToILRepack.patch
    %patch -p1 --binary < $pkgfiles/FixNuGet.exeILMerge.patch
    msbuild -t:Restore build/bootstrap.proj
    msbuild -t:Restore src/NuGet.Clients/NuGet.CommandLine
build      : |
    msbuild src/NuGet.Clients/NuGet.CommandLine -p:Configuration=Release
install    : |
    install -Dm00644 artifacts/VS15/NuGet.exe $installdir/%libdir%/nuget/NuGet.exe
    install -Dm00644 artifacts/NuGet.CommandLine/16.0/bin/Release/net472/NuGet.Core.dll $installdir/%libdir%/nuget/
    install -Dm00644 artifacts/NuGet.CommandLine/16.0/bin/Release/net472/Microsoft.Web.XmlTransform.dll $installdir/%libdir%/nuget/
    install -Dm00755 $pkgfiles/nuget $installdir/usr/bin/nuget
